[package]
name = "orca-rs"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "orca_rs"
crate-type = ["cdylib", "lib"]

[dependencies]
pyo3 = "0.19.0"
